### ISSUE TITLE
is it open source game?

### ISSUE THREAD

**Issue by vgkgopalsaroja** [gottfired/flutter_puzzle#1]

**Comment by gottfired** [comment]
I've added a license file.

**Comment by gottfired** [comment]
@vgkgopalsaroja Did you by any chance release the game to the iOS App Store? The license does not allow production use. I am only releasing the source code for other people to learn. I am asking, because I wanted to release my game and it got rejected because there is an identical game released in another region.

**Comment by vgkgopalsaroja** [comment]
No, I already saw your license, it not allow to use production use, so that i am not using your code.

My application and games available following links:
https://play.google.com/store/apps/developer?id=ArunaAnanth
https://play.google.com/store/apps/developer?id=vgk_gopal
